[motobug]

[[motobug.animations]]
name = "Stopped"
id = 0
duration = 12
frames = [[0, 96, 40, 32]]
loopback = 0

[[motobug.animations]]
name = "Walking"
id = 1
duration = 6
frames = [
       [0,  0, 40, 32],
       [0, 32, 40, 32],
       [0, 64, 40, 32],
       [0, 96, 40, 32],
]
loopback = 0

# ============

[buzzbomber]

[[buzzbomber.animations]]
name = "Idle"
id = 0
duration = 0
loopback = 0
frames = [[40, 0, 49, 29]]

[[buzzbomber.animations]]
name = "Firing"
id = 1
duration = 0
loopback = 0
frames = [[40, 32, 49, 29]]

[buzzbomber.fragment]
offset = [3, -23]

[[buzzbomber.fragment.animations]]
name = "Wings"
id = 0
duration = 2
loopback = 0
frames = [
       [51, 61, 38, 8],
       [51, 69, 38, 8],
]

# ============

[projectile]

[[projectile.animations]]
name = "buzzbomber_charge"
id = 0
duration = 6
loopback = 3
frames = [
       [89,  0, 16, 16],
       [89,  0, 16, 16],
       [89, 16, 16, 16],
       [89, 16, 16, 16],
]

[[projectile.animations]]
name = "buzzbomber_fire"
id = 1
duration = 12
loopback = 0
frames = [
       [89, 32, 16, 16],
       [89, 48, 16, 16],
]


# ============

[chopper]

[[chopper.animations]]
name = "Idle"
id = 0
duration = 6
loopback = 0
frames = [
       [106,  0, 32, 32],
       [106, 32, 32, 32],
]

# ============

[boss_spawner]
# Spawner object has no animations
# When triggered, destroys itself and spawns a free object

# ============

[boss]

[[boss.animations]]
name = "eggmobile"
id = 0
duration = 30
loopback = 0
frames = [
       [0, 256, 64, 48],
       [0, 320, 64, 48],
]
