[clouds1]
u0 = 0
v0 = 256
width = 256
height = 41
single = false
scrollx = 0.07
speedx = 0.07
y0 = 0

[clouds2]
u0 = 0
v0 = 256
width = 256
height = 41
single = false
scrollx = 0.072
speedx = 0.072
y0 = 41

# ===========

[high_city]
u0 = 0
v0 = 144
width = 256
height = 80
single = false
scrollx = 0.05
speedx = 0.0
y0 = 25

[water_surface]
u0 = 0
v0 = 224
width = 256
height = 8
single = false
scrollx = 0.055
speedx =  0.0
y0 = 105

[water1]
u0 = 0
v0 = 232
width = 256
height = 8
single = false
scrollx = 0.06
speedx = 0.06
y0 = 113

[water2]
u0 = 0
v0 = 239
width = 256
height = 10
single = false
scrollx = 0.07
speedx = 0.07
y0 = 121

[water3]
u0 = 0
v0 = 239
width = 256
height = 10
single = false
scrollx = 0.08
speedx = 0.08
y0 = 131

[water4]
u0 = 0
v0 = 239
width = 256
height = 10
single = false
scrollx = 0.09
speedx = 0.09
y0 = 141

# =========

[city1]
u0 = 0
v0 = 0
width = 256
height = 64
single = false
scrollx = 0.1
speedx =  0.0
y0 = 96

[city2]
u0 = 0
v0 = 0
width = 128
height = 64
single = false
scrollx = 0.12
speedx =  0.0
y0 = 120

[city3]
u0 = 0
v0 = 64
width = 256
height = 80
single = false
scrollx = 0.14
speedx = 0.0
y0 = 160
