[ring]

[[ring.animations]]
name = "idle"
id = 0
# Frames: u, v, w, h
frames = [
    [16, 0, 16, 16],
    [32, 0, 16, 16],
    [48, 0,  8, 16],
    [56, 0, 16, 16],
]
loopback = 0

[[ring.animations]]
name = "destroyed"
id = 1
frames = [
    [72, 0, 16, 16],
    [88, 0, 16, 16],
    [104, 0, 16, 16],
    [120, 0, 16, 16],
]
loopback = -1

# ============

[monitor]

[[monitor.animations]]
name = "normal"
id = 0
frames = [[136, 0, 32, 32]]
loopback = 0

[[monitor.animations]]
name = "destroyed"
id = 1
frames = [[224, 32, 31, 16]]
loopback = 0

# ------------

[monitor.fragment]
offset = [0, -10]

[[monitor.fragment.animations]]
id = 0
name = "none"
frames = [
    [168, 0, 16, 16],
    [184, 0, 16, 16],
    [200, 0, 16, 16],
]
loopback = 0

[[monitor.fragment.animations]]
id = 1
name = "ring"
frames = [
    [168, 0, 16, 16],
    [216, 0, 16, 16],
]
loopback = 0

[[monitor.fragment.animations]]
id = 2
name = "speedshoes"
frames = [
    [168, 0, 16, 16],
    [232, 0, 16, 16],
]
loopback = 0

[[monitor.fragment.animations]]
id = 3
name = "shield"
frames = [
    [168, 0, 16, 16],
    [168, 16, 16, 16],
]
loopback = 0

[[monitor.fragment.animations]]
id = 4
name = "invincibility"
frames = [
    [168, 0, 16, 16],
    [184, 16, 16, 16],
]
loopback = 0

[[monitor.fragment.animations]]
id = 5
name = "1up"
frames = [
    [168, 0, 16, 16],
    [200, 16, 16, 16],
]
loopback = 0

[[monitor.fragment.animations]]
id = 6
name = "super"
frames = [
    [168, 0, 16, 16],
    [216, 16, 16, 16],
]
loopback = 0

# ============

[spikes]

[[spikes.animations]]
name = "none"
id = 0
frames = [[0, 16, 32, 32]]
loopback = 0

# ============

[checkpoint]

[[checkpoint.animations]]
name = "none"
id = 0
frames = [[32, 32, 16, 48]]
loopback = 0

# ------------

[checkpoint.fragment]
offset = [0, -48]


[[checkpoint.fragment.animations]]
name = "inactive"
id = 0
frames = [[32, 16, 16, 16]]
loopback = 0

[[checkpoint.fragment.animations]]
name = "active"
id = 1
frames = [
    [0, 48, 16, 16],
    [16, 48, 16, 16],
]
loopback = 0


# ============

[spring_yellow]

[[spring_yellow.animations]]
name = "idle"
id = 0
frames = [[80, 16, 32, 16]]
loopback = 0

[[spring_yellow.animations]]
name = "bounce"
id = 1
frames = [
    [80, 32, 32, 8],
    [80, 40, 32, 40],
]
loopback = -1

# ============

[spring_red]

[[spring_red.animations]]
name = "idle"
id = 0
frames = [[48, 16, 32, 16]]
loopback = 0

[[spring_red.animations]]
name = "bounce"
id = 1
frames = [
    [48, 32, 32, 8],
    [48, 40, 32, 40],
]
loopback = -1

# ============

[spring_yellow_diagonal]

[[spring_yellow_diagonal.animations]]
name = "idle"
id = 0
frames = [[112, 80, 32, 32]]
loopback = 0

[[spring_yellow_diagonal.animations]]
name = "bounce"
id = 1
frames = [
    [144, 80, 32, 32],
    [176, 80, 48, 48],
]
loopback = -1

# ============

[spring_red_diagonal]

[[spring_red_diagonal.animations]]
name = "idle"
id = 0
frames = [[112, 32, 32, 32]]
loopback = 0

[[spring_red_diagonal.animations]]
name = "bounce"
id = 1
frames = [
    [144, 32, 32, 32],
    [176, 32, 48, 48],
]
loopback = -1

# ============

[goal_sign]

[[goal_sign.animations]]
name = "none"
id = 0
frames = [[0, 80, 48, 56]]
loopback = 0

[[goal_sign.animations]]
name = "spin"
id = 1
frames = [
    # x, y, w, h, flip_x, flip_y
    [0,  80, 48, 56, 0, 0],
    [48, 80, 32, 56, 0, 0],
    [80, 80, 32, 56, 0, 0],
    [48, 80, 32, 56, 1, 0],
    [0, 136, 48, 56, 0, 0],
    [48, 80, 32, 56, 0, 0],
    [80, 80, 32, 56, 0, 0],
    [48, 80, 32, 56, 1, 0],
]
loopback = 0

[[goal_sign.animations]]
name = "win_sonic"
id = 2
frames = [[0, 136, 48, 56]]
loopback = 0

# ============

[switch]

[[switch.animations]]
name = "inactive"
id = 0
frames = [[112, 64, 32, 16]]
loopback = 0

[[switch.animations]]
name = "active"
id = 1
frames = [[144, 72, 32, 8]]
loopback = 0

# ============
# Dummy objects
# ============

[ring_3h]
dummy = true

[ring_3v]
dummy = true
