[ring]

[[ring.animations]]
name = "idle"
id = 0
duration = 6
# Frames: u, v, w, h
frames = [
    [16, 0, 16, 16],
    [32, 0, 16, 16],
    [48, 0,  8, 16],
    [56, 0, 16, 16],
]
loopback = 0

[[ring.animations]]
name = "destroyed"
id = 1
duration = 6
frames = [
    [72, 0, 16, 16],
    [88, 0, 16, 16],
    [104, 0, 16, 16],
    [120, 0, 16, 16],
]
loopback = -1

# ============

[monitor]

[[monitor.animations]]
name = "normal"
id = 0
duration = 0
frames = [[136, 0, 32, 32]]
loopback = 0

[[monitor.animations]]
name = "destroyed"
id = 1
duration = 0
frames = [[224, 32, 31, 16]]
loopback = 0

# ------------

[monitor.fragment]
offset = [0, -12]

[[monitor.fragment.animations]]
id = 0
name = "none"
duration = 3
frames = [
    [168, 0, 16, 16],
    [184, 0, 16, 16],
    [200, 0, 16, 16],
]
loopback = 0

[[monitor.fragment.animations]]
id = 1
name = "ring"
duration = 2
frames = [
    [168, 0, 16, 16],
    [216, 0, 16, 16],
    [216, 0, 16, 16],
]
loopback = 0

[[monitor.fragment.animations]]
id = 2
name = "speedshoes"
duration = 2
frames = [
    [168, 0, 16, 16],
    [232, 0, 16, 16],
    [232, 0, 16, 16],
]
loopback = 0

[[monitor.fragment.animations]]
id = 3
name = "shield"
duration = 2
frames = [
    [168, 0, 16, 16],
    [168, 16, 16, 16],
    [168, 16, 16, 16],
]
loopback = 0

[[monitor.fragment.animations]]
id = 4
name = "invincibility"
duration = 2
frames = [
    [168, 0, 16, 16],
    [184, 16, 16, 16],
    [184, 16, 16, 16],
]
loopback = 0

[[monitor.fragment.animations]]
id = 5
name = "sonic"
duration = 2
frames = [
    [168, 0, 16, 16],
    [200, 16, 16, 16],
    [200, 16, 16, 16],
]
loopback = 0

[[monitor.fragment.animations]]
id = 6
name = "super"
duration = 2
frames = [
    [168, 0, 16, 16],
    [216, 16, 16, 16],
    [216, 16, 16, 16],
]
loopback = 0

[[monitor.fragment.animations]]
id = 7
name = "miles"
duration = 2
frames = [
    [168, 0, 16, 16],
    [232, 16, 16, 16],
    [232, 16, 16, 16],
]
loopback = 0

[[monitor.fragment.animations]]
id = 8
name = "knuckles"
duration = 2
frames = [
    [168, 0, 16, 16],
    [144, 112, 16, 16],
    [144, 112, 16, 16],
]
loopback = 0

# ============

[spikes]

[[spikes.animations]]
name = "none"
id = 0
duration = 0
frames = [[0, 16, 32, 32]]
loopback = 0

# ============

[checkpoint]

[[checkpoint.animations]]
name = "none"
id = 0
duration = 0
frames = [[32, 32, 16, 48]]
loopback = 0

# ------------

[checkpoint.fragment]
offset = [0, -48]


[[checkpoint.fragment.animations]]
name = "inactive"
id = 0
duration = 0
frames = [[32, 16, 16, 16]]
loopback = 0

[[checkpoint.fragment.animations]]
name = "active"
id = 1
duration = 4
frames = [
    [0, 48, 16, 16],
    [16, 48, 16, 16],
]
loopback = 0


# ============

[spring_yellow]

[[spring_yellow.animations]]
name = "idle"
id = 0
duration = 0
frames = [[80, 16, 32, 16]]
loopback = 0

[[spring_yellow.animations]]
name = "bounce"
id = 1
duration = 4
frames = [
    [80, 32, 32, 8],
    [80, 40, 32, 40],
]
loopback = -1

# ============

[spring_red]

[[spring_red.animations]]
name = "idle"
id = 0
duration = 0
frames = [[48, 16, 32, 16]]
loopback = 0

[[spring_red.animations]]
name = "bounce"
id = 1
duration = 4
frames = [
    [48, 32, 32, 8],
    [48, 40, 32, 40],
]
loopback = -1

# ============

[spring_yellow_diagonal]

[[spring_yellow_diagonal.animations]]
name = "idle"
id = 0
duration = 0
frames = [[112, 80, 32, 32]]
loopback = 0

[[spring_yellow_diagonal.animations]]
name = "bounce"
id = 1
duration = 4
frames = [
    [144, 80, 32, 32],
    [176, 80, 48, 48],
]
loopback = -1

# ============

[spring_red_diagonal]

[[spring_red_diagonal.animations]]
name = "idle"
id = 0
duration = 0
frames = [[112, 32, 32, 32]]
loopback = 0

[[spring_red_diagonal.animations]]
name = "bounce"
id = 1
duration = 4
frames = [
    [144, 32, 32, 32],
    [176, 32, 48, 48],
]
loopback = -1

# ============

[goal_sign]

# Goal sign is originally 40x56

[[goal_sign.animations]]
name = "none"
id = 0
duration = 0
frames = [[0, 80, 24, 56]]
loopback = 0

# -----------

[goal_sign.fragment]
offset = [0, -24]

[[goal_sign.fragment.animations]]
id = 0
duration = 0
name = "robotnik"
frames = [[0, 256, 48, 32]]
loopback = 0

[[goal_sign.fragment.animations]]
id = 1
name = "spin"
duration = 1
frames = [
       # x, y, w, h, flip_x, flip_y
       [ 0, 256, 48, 32],       # Robotnik
       [ 0, 136, 32, 32, 0, 0], # flip 1
       [32, 136,  8, 32, 0, 0], # flip 2
       [ 0, 288, 48, 32],       # Sonic
       [32, 136,  8, 32, 1, 0], # flip 2 x
       [ 0, 136, 32, 32, 1, 0], # flip 1 x
       [48, 256, 48, 32],       # Miles
       [ 0, 136, 32, 32, 0, 0], # flip 1
       [32, 136,  8, 32, 0, 0], # flip 2
       [48, 288, 48, 32],       # Knuckles
       [32, 136,  8, 32, 1, 0], # flip 2 x
       [ 0, 136, 32, 32, 1, 0], # flip 1 x
]
loopback = 0

[[goal_sign.fragment.animations]]
id = 2
name = "win_sonic"
duration = 0
frames = [[0, 288, 48, 32]]
loopback = 0

[[goal_sign.fragment.animations]]
id = 3
name = "win_miles"
duration = 0
frames = [[48, 256, 48, 32]]
loopback = 0

[[goal_sign.fragment.animations]]
id = 4
name = "win_knuckles"
duration = 0
frames = [[48, 288, 48, 32]]
loopback = 0

# ============

[switch]

[[switch.animations]]
name = "inactive"
id = 0
duration = 0
frames = [[112, 64, 32, 16]]
loopback = 0

[[switch.animations]]
name = "active"
id = 1
duration = 0
frames = [[144, 72, 32, 8]]
loopback = 0


# ============

[explosion]

[[explosion.animations]]
name = "small"
id = 0
duration = 4
frames = [
       [48, 136, 32, 32],
       [80, 136, 32, 32],
       [112, 136, 32, 32],
       [144, 136, 47, 47],
       [192, 136, 47, 47],
]
loopback = -1

[[explosion.animations]]
name = "big"
id = 1
duration = 4
frames = [
       [48, 136, 32, 32],
       [80, 168, 32, 32],
       [112, 168, 32, 32],
       [144, 136, 47, 47],
       [192, 136, 47, 47],
]
loopback = -1

[[explosion.animations]]
name = "splash"
id = 2
duration = 2
frames = [
       [146, 192, 22, 32],
       [172, 192, 32, 32],
       [205, 192, 32, 32],
       [146, 224, 31, 31],
       [177, 224, 31, 31],
       [208, 224, 32, 31],
       #[111, 112, 32, 24],
]
loopback = -1

# ============

[monitor_image]

[[monitor_image.animations]]
id = 0
name = "none"
duration = 3
frames = [
    [168, 0, 16, 16],
    [184, 0, 16, 16],
    [200, 0, 16, 16],
]
loopback = 0

[[monitor_image.animations]]
id = 1
name = "ring"
duration = 2
frames = [[216, 0, 16, 16]]
loopback = 0

[[monitor_image.animations]]
id = 2
name = "speedshoes"
duration = 2
frames = [[232, 0, 16, 16]]
loopback = 0

[[monitor_image.animations]]
id = 3
name = "shield"
duration = 2
frames = [[168, 16, 16, 16]]
loopback = 0

[[monitor_image.animations]]
id = 4
name = "invincibility"
duration = 2
frames = [[184, 16, 16, 16]]
loopback = 0

[[monitor_image.animations]]
id = 5
name = "sonic"
duration = 2
frames = [[200, 16, 16, 16]]
loopback = 0

[[monitor_image.animations]]
id = 6
name = "super"
duration = 2
frames = [[216, 16, 16, 16]]
loopback = 0

[[monitor_image.animations]]
id = 7
name = "miles"
duration = 2
frames = [[232, 16, 16, 16]]
loopback = 0

[[monitor_image.animations]]
id = 8
name = "knuckles"
duration = 2
frames = [[144, 112, 16, 16]]
loopback = 0

# ============

[shield]

[[shield.animations]]
id = 0
name = "default"
duration = 4
frames = [
    [50, 204, 48, 41, 1, 0],
    [98, 204, 48, 41],
    [50, 204, 48, 41],
]
loopback = 0


# ============

[bubble_patch]

[[bubble_patch.animations]]
id = 0
name = "default"
duration = 16
frames = [
       [16, 206, 16, 16],
       [32, 206, 16, 16],
]
loopback = 0

# ============

[bubble]

[[bubble.animations]]
id = 0
name = "small"
duration = 8
frames = [
       [ 2, 194,  4,  4],
       [ 8, 192,  8,  8],
]
loopback = 1

[[bubble.animations]]
id = 1
name = "medium"
duration = 8
frames = [
       [ 2, 194,  4,  4],
       [ 8, 192,  8,  8],
       [18, 194, 12, 12],
]
loopback = 2

[[bubble.animations]]
id = 2
name = "big"
duration = 8
frames = [
       [ 2, 194,  4,  4],
       [ 8, 192,  8,  8],
       [18, 194, 12, 12],
       [ 0, 200, 16, 16],
       [ 0, 222, 23, 23],
       [48, 172, 32, 32],
]
loopback = 5

# ---- number animations ----
[[bubble.animations]]
id = 3
name = "number 5"
duration = 8
frames = [
       [ 2, 194,  4,  4],
       [ 2, 194,  4,  4],
       [ 8, 192,  8,  8],
       [18, 194, 12, 12],
       [18, 194, 12, 12],
       [239, 52, 16, 20],
       [0, 0, 0, 0],
       [239, 52, 16, 20],
       [0, 0, 0, 0],
       [239, 52, 16, 20],
]
loopback = -1

[[bubble.animations]]
id = 4
name = "number 4"
duration = 8
frames = [
       [ 2, 194,  4,  4],
       [ 2, 194,  4,  4],
       [ 8, 192,  8,  8],
       [18, 194, 12, 12],
       [18, 194, 12, 12],
       [239, 72, 16, 20],
       [0, 0, 0, 0],
       [239, 72, 16, 20],
       [0, 0, 0, 0],
       [239, 72, 16, 20],
]
loopback = -1

[[bubble.animations]]
id = 5
name = "number 3"
duration = 8
frames = [
       [ 2, 194,  4,  4],
       [ 2, 194,  4,  4],
       [ 8, 192,  8,  8],
       [18, 194, 12, 12],
       [18, 194, 12, 12],
       [239, 92, 16, 20],
       [0, 0, 0, 0],
       [239, 92, 16, 20],
       [0, 0, 0, 0],
       [239, 92, 16, 20],
]
loopback = -1

[[bubble.animations]]
id = 6
name = "number 2"
duration = 8
frames = [
       [ 2, 194,  4,  4],
       [ 2, 194,  4,  4],
       [ 8, 192,  8,  8],
       [18, 194, 12, 12],
       [18, 194, 12, 12],
       [239, 112, 16, 20],
       [0, 0, 0, 0],
       [239, 112, 16, 20],
       [0, 0, 0, 0],
       [239, 112, 16, 20],
]
loopback = -1

[[bubble.animations]]
id = 7
name = "number 1"
duration = 8
frames = [
       [ 2, 194,  4,  4],
       [ 2, 194,  4,  4],
       [ 8, 192,  8,  8],
       [18, 194, 12, 12],
       [18, 194, 12, 12],
       [239, 132, 16, 20],
       [0, 0, 0, 0],
       [239, 132, 16, 20],
       [0, 0, 0, 0],
       [239, 132, 16, 20],
]
loopback = -1

[[bubble.animations]]
id = 8
name = "number 0"
duration = 8
frames = [
       [ 2, 194,  4,  4],
       [ 2, 194,  4,  4],
       [ 8, 192,  8,  8],
       [18, 194, 12, 12],
       [18, 194, 12, 12],
       [239, 152, 16, 20],
       [0, 0, 0, 0],
       [239, 152, 16, 20],
       [0, 0, 0, 0],
       [239, 152, 16, 20],
]
loopback = -1


# ============
[end_capsule]

[[end_capsule.animations]]
id = 0
name = "default"
duration = 0
frames = [[96, 320, 64, 64]]
loopback = 0

[[end_capsule.animations]]
id = 0
name = "open"
duration = 0
frames = [[96, 256, 64, 64]]
loopback = 0

# [end_capsule.fragment]
# offset = [0, -16]

# [[end_capsule.fragment.animations]]
# id = 0
# name = "default"
# duration = 0
# loopback = 0
# frames = [[160, 288, 64, 24]]


# ============
[end_capsule_button]

[[end_capsule_button.animations]]
id = 0
name = "default"
duration = 0
loopback = 0
frames = [[160, 256, 32, 17]]

[[end_capsule_button.animations]]
id = 1
name = "pressed"
duration = 0
loopback = 0
frames = [[160, 256, 32, 8]]

# ============

[door]

[[door.animations]]
id = 0
name = "default"
duration = 0
loopback = 0
frames = [[224, 256, 16, 64]]

# ============

[animal]

# ------------

[[animal.animations]]
id = 0
name = "flicky_stop"
duration = 0
loopback = 0
frames = [[160, 312, 16, 24]]

[[animal.animations]]
id = 1
name = "flicky_up"
duration = 0
loopback = 0
frames = [[176, 312, 16, 16]]

[[animal.animations]]
id = 2
name = "flicky_down"
duration = 0
loopback = 0
frames = [[192, 312, 16, 16]]

# ------------

# ============
# Dummy objects
# ============

[ring_3h]
dummy = true

[ring_3v]
dummy = true

[startpos]
dummy = true
