[clouds0]
width = 64
height = 16
u0 = 0
v0 = 0
scrollx = 0.5
speedx = 0
y0 = 0
single = false

[clouds1]
width = 64
height = 16
u0 = 0
v0 = 16
scrollx = 0.45
speedx = 0
y0 = 16
single = false

[clouds2]
width = 64
height = 10
u0 = 0
v0 = 32
scrollx = 0.4
speedx = 0
y0 = 32
single = false

[clouds3]
width = 64
height = 13
u0 = 0
v0 = 42
scrollx = 0.35
speedx = 0
y0 = 42
single = false

[buildings]
width = 256
height = 112
u0 = 0
v0 = 55
scrollx = 0.2
speedx = 0
y0 = 100
single = false

