[ballhog]

[[ballhog.animations]]
name = "Idle"
id = 0
duration = 12
frames = [
       [0, 0, 24, 40],
       [24, 0, 24, 40],
]
loopback = 0

[[ballhog.animations]]
name = "Release"
id = 1
duration = 12
frames = [
       [0, 40, 24, 40],
       [24, 40, 24, 40],
       [24, 40, 24, 40],
]
loopback = 2

# ============
[bouncebomb]

[[bouncebomb.animations]]
name = "Default"
id = 0
duration = 6
frames = [
       [48, 0, 16, 16],
       [48, 16, 16, 16],
]
loopback = 0

# ===========

[boss_spawner]
# Spawner object has no animations
# When triggered, destroys itself and spawns a free object

# ============
[boss]

[[boss.animations]]
name = "Default"
id = 0
duration = 12
frames = [[0, 256, 64, 64]]
loopback = 0

[boss.fragment]
offset = [0, -47]

[[boss.fragment.animations]]
id = 0
name = "head_normal"
duration = 12
frames = [[64, 256, 56, 16]]
loopback = 0

[[boss.fragment.animations]]
id = 1
name = "head_down"
duration = 12
frames = [[64, 272, 56, 16]]
loopback = 0

[[boss.fragment.animations]]
id = 2
name = "head_hit"
duration = 12
frames = [[64, 288, 56, 16]]
loopback = 0

[[boss.fragment.animations]]
id = 3
name = "head_dead"
duration = 12
frames = [[64, 304, 56, 16]]
loopback = 0

[[boss.fragment.animations]]
id = 4
name = "head_recovering"
duration = 12
frames = [[64, 320, 56, 16]]
loopback = 0

[[boss.fragment.animations]]
id = 5
name = "head_dropping"
duration = 12
frames = [[64, 336, 56, 16]]
loopback = 0